### ISSUE TITLE
Integration Request

### ISSUE THREAD

**Issue by DraconicArcher** [Christofmeg/JustEnoughBreeding#13]
I'm on Forge 1.19.2 Can you add integration for Alex's Mobs (Like you did for 1.20, and for Critters and Companions, and Creatures and Beasts?

**Comment by Christofmeg** [comment]
I'll backport every feature from 1.20 to 1.19.
Will look into the mods you suggested.

**Comment by Christofmeg** [comment]
Integration to Alex's Mobs is backported from 1.20.x in version 1.2.0 for 1.19.x
Integration to the other mods will be in version 1.2.1, when I finish that.

**Comment by DraconicArcher** [comment]
Thank you so much!
