### ISSUE TITLE
Mod Integration Suggestions

### ISSUE THREAD

**Issue by Cicopath** [Christofmeg/JustEnoughBreeding#17]
Hi! I saw that rather than adding mods via datapack, we can suggest mod integrations on here. I'd like to suggest a few mods if that's perfectly fine with you. I don't know which versions are supported, so I'll list whether they have 1.19.2 or 1.20.1. All of the mods listed below should have mob that are breedable, though I may be mistaken:

**Forge**
[[Let's Do] BloomingNature](https://www.curseforge.com/minecraft/mc-mods/lets-do-bloomingnature/screenshots) (1.20.1)
[[Let's Do] Meadow](https://www.curseforge.com/minecraft/mc-mods/lets-do-meadow) (1.19.2 & 1.20.1)
[Environmental](https://www.curseforge.com/minecraft/mc-mods/environmental) (1.19.2)
[Neapolitan](https://www.curseforge.com/minecraft/mc-mods/neapolitan) (1.19.2 & 1.20.1)
[Fish of Thieves](https://www.curseforge.com/minecraft/mc-mods/fish-of-thieves) (1.19.2 & 1.20.1)

**Fabric**
[[Let's Do] BloomingNature](https://www.curseforge.com/minecraft/mc-mods/lets-do-bloomingnature/screenshots) (1.20.1)
[[Let's Do] Meadow](https://www.curseforge.com/minecraft/mc-mods/lets-do-meadow) (1.19.2 & 1.20.1)
[Fish of Thieves](https://www.curseforge.com/minecraft/mc-mods/fish-of-thieves) (1.19.2 & 1.20.1)
[Promenade](https://www.curseforge.com/minecraft/mc-mods/promenade) (1.19.2 & 1.20.1)
[Fish of Thieves](https://www.curseforge.com/minecraft/mc-mods/fish-of-thieves) (1.19.2 & 1.20.1)

I also have a question: If we add additional breeding items for mobs (e.g. a vanilla cow) through a mod such as KubeJS, would the new breedable item show in the JEI/REI/EMI menu? I know mods like Naturalist and Environmental use item tags for breeding/food items last I checked.

Thank you!

**Comment by Christofmeg** [comment]
All mobs that have a tag associated with them, will be dynamic. If you edit what the tag contains, then it will show that instead.
For cows in particular minecraft used to have minecraft:wheat pre 1.20.6, but used the tag minecraft:cow_food on 1.20.6+

**Comment by Christofmeg** [comment]
@Cicopath you wrote Fish Of Thieves twice under Fabric. Was it meant to be something else?

**Comment by Cicopath** [comment]
Oh whoops! I think I thought it was something else and so I edited my message to add it again lol. It was not meant to be something else

**Comment by Christofmeg** [comment]
It seems like Fish of Thieves has an upcoming feature where they'll implement a [Breeding System](https://github.com/users/SteveKunG/projects/1?pane=issue&itemId=70599174). So I won't be making an integration before that system is implemented.

**Comment by Christofmeg** [comment]
Implemented in version 1.4.0
