### ISSUE TITLE
1.20.1 version is Forge or Neoforge?

### ISSUE THREAD

**Issue by uhloin** [Christofmeg/JustEnoughBreeding#19]
The last version for 1.20.1 on the curseforge site is marked as Forge, but name is like for NeoForge:

https://www.curseforge.com/minecraft/mc-mods/justenoughbreeding/files/5534885

**Comment by Christofmeg** [comment]
I'm going to fix that

**Comment by Christofmeg** [comment]
It might have been a bug in the Gradle plugin I use for uploading to CurseForge. I've manually updated it to NeoForge, and it should soon be synchronized on CurseForge. I'll make sure to prevent this from happening again. Thanks for reporting it!
