### ISSUE TITLE
Integration Request Pam's Harvestcraft

### ISSUE THREAD

**Issue by gaminggirl** [Christofmeg/JustEnoughBreeding#20]
I'd like to suggest Pam's Harvestcraft to the list of mods to integrate into the mod. It has a lot of new foods that animals can breed with.

**Comment by Christofmeg** [comment]
What modloader, version of Minecraft and Pam's Harvestcraft are you referring to? 

I tested Pam's Harvestcraft - Crops on Minecraft versions 1.20.1, 1.20.4, and 1.21. I concluded that it only adds a TemptationTask (where animals are tempted with food but it does not make them breedable).

This is the info I found on the mod page for Pam's Harvestcraft - Crops:

> **Animal Behaviors Added**
>
> - Cows, Sheep now follow/breed with Amaranth, Barley, Bean, Chickpea, Corn, Lentil, Mustard Seeds (item), Oats, Quinoa, Rice, Rye, Soybean
>
> - Pigs now follow/breed with Arrowroot, Artichoke, Asparagus, Bellpepper, Broccoli, Brusselsprout, Cabbage, Cassava, Cauliflower, Celery, Chilipepper, Cucumber, Eggplant, Garlic, Jicama, Kale, Kohlrabi, Leek, Lettuce, Okra, Onion, Parsnip, Peanut, Peas, Radish, Rhubarb, Rutabaga, Scallion, Spinach, Sweet Potato, Taro, Tomatillo, Tomato, Turnip, Water Chestnut, Winter Squash, Zucchini
>
> - Rabbits now follow/breed with Blackberry, Blueberry, Cactusfruit, Candleberry, Cantaloupe, Cranberry, Elderberry, Grape, Green Grape, Huckleberry, Juniperberry, Kiwi, Melon Slice, Mulberry, Pineapple, Raspberry, Spiceleaf, Strawberry, and Sweet Berries
>
> - Chickens now follow/breed with every seed known to man

**Comment by gaminggirl** [comment]
Modloader: Forge 
Minecraft: 1.20.1
Pams: Pam's Harvestcraft - Crops

I found the info that you linked and concluded it meant animals bred with those items. But the mod did not show any of them...

**Comment by Christofmeg** [comment]
1.16.5 is the newest version of Pam's Harvestcraft 2 - Crops where breeding with mobs works.

I've added this issue to a private project, so if I one day decide to backport the latest features of Just Enough Breeding to 1.16.5. Then I'll add an integration to Pam's Harvestcraft 2 - Crops.
