### ISSUE TITLE
GUI missing textures

### ISSUE THREAD

**Issue by Jous4n** [Christofmeg/JustEnoughBreeding#22]
![image](https://github.com/user-attachments/assets/0fbbb4c7-3109-4f11-8d42-46811476473d)

**Comment by Christofmeg** [comment]
What version of JEI and Just Enough Breeding are you using?

**Comment by Jous4n** [comment]
1.4.0 for 1.20.1

**Comment by Christofmeg** [comment]
Update Just Enough Items to the latest version.

Tested with:
 * jei-1.20.1-forge-15.12.2.51.jar
 * justenoughbreeding-forge-1.20.x-1.4.0.jar


![2024-09-27_07 06 10](https://github.com/user-attachments/assets/c25815c5-b8de-4eb1-8bdd-cccf3485d05e)

**Comment by Jous4n** [comment]
That's not the latest version for JEI. Current latest version for it is 15.20.0.101. Issue persists.
I'm also using these other JEI-related mods:
- Just Enough Professions 3.0.1
- Just Enough Resources 1.4.0.247
- Just Enough Effect Descriptions 2.2.2

All for 1.20.1

**Comment by Christofmeg** [comment]
jei-1.20.1-forge-15.19.4.94 is the last working beta version of JEI, where the texture is not missing.
Something changed in jei-1.20.1-forge-15.19.5.95, I'll look into it.

**Comment by Jous4n** [comment]
Oh I see. Yeah, I'll be using JEI 15.19.4.94 instead of its 15.19.5.95 version, thanks.

**Comment by Christofmeg** [comment]
Issue will be fixed in Just Enough Breeding version 1.4.1

**Comment by Jous4n** [comment]
Awesome! Thanks!
