### ISSUE TITLE
1.4.1 Quilt is broken on 1.20.1

### ISSUE THREAD

**Issue by NolanHewitt** [Christofmeg/JustEnoughBreeding#25]
Seems something went wrong with this version. Majority of the animals are missing ( I went from 20 pages of animals in 1.4.0 to 4 pages with 1.4.1) and it doesn't show any of the items usable for breeding except for wheat. 1.4.0 works without issue.

I'm using EMI.

**Comment by Christofmeg** [comment]
What version of EMI and Quilt are you using?

EMI on Quilt did not get any changes from 1.4.0 to 1.4.1
![image](https://github.com/user-attachments/assets/c25528de-9f7c-4436-ac87-eeca178c4204)

**Comment by NolanHewitt** [comment]
I’m using EMI 1.1.16, and quilt loader 0.26.4

I do have JEI installed as well to make use of EMI’s compatability with its recipes in case that’s important, for that I’m using 15.20.0.104

**Comment by Christofmeg** [comment]
emi-1.1.16+1.20.1+fabric
jei-1.20.1-fabric-15.20.0.104
justenoughbreeding-quilt-1.20.x-1.4.1
qfapi-7.6.0_qsl-6.2.0_fapi-0.92.2_mc-1.20.1
Quilt 0.26.4

https://github.com/user-attachments/assets/cdd6e092-f943-46c9-802c-1d4db247c8b0

**Comment by NolanHewitt** [comment]
Looks like it was a compatibility issue with a certain mod.
