### ISSUE TITLE
Flashing variants

### ISSUE THREAD

**Issue by SiverDX** [Christofmeg/JustEnoughBreeding#4]
Forge 1.19.2 using EMI + JEI, version 1.0.0

https://github.com/Christofmeg/JustEnoughBreeding/blob/814f5bac1f3302ed464d957046f015cd72420673/Forge/src/main/java/com/christofmeg/justenoughbreeding/jei/BreedingCategory.java#L136

I'm not entirely sure but this might cause a potentially new variant to be picked for rendering (each tick) resulting in this:
https://streamable.com/ktnsmt

You could create the entity and hold it for 5 seconds (100 ticks) (or 3 seconds) and then create a new one as an alternative for showing variants

(Also is it intentional that the entity is looking in the opposite direction of the cursor?)

**Comment by Christofmeg** [comment]
Yeah, the mob rendering needs some polishing
