### ISSUE TITLE
Fabric 1.20.x version not recognizing REI.

### ISSUE THREAD

**Issue by Gamemassa** [Christofmeg/JustEnoughBreeding#6]
Hi, I love your mod, and I've added it to both of my custom modpacks (one on Forge 1.20.x and one on Fabric 1.20.x), ~~and I noticed that the Forge version seems to work with REI as well as JEI, but the Fabric version doesn't see REI and just tells me "JEI is missing". Please Disregard. I'm assuming it works with REI because the REI team added an REI Plugin Compatibility mod for Forge.~~

**Comment by Gamemassa** [comment]
I also didn't realize there was a newer version of JustEnoughBreeding available. Updating to that seems to ~~have fixed my issue~~ be allowing Fabric 1.20.x to launch with JustEnoughBreeding and REI, but in-game I can't see Breeding info.

**Comment by Christofmeg** [comment]
That is because I am yet to implement official REI support.

**Comment by Gamemassa** [comment]
Oh. I'm assuming it's planned, though, based on that response (which makes me excited).

**Comment by Christofmeg** [comment]
@Gamemassa Implemented in version 1.1.0
